config/routes.rb
Rails.application.routes.draw do
  resources :user_registrations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :posts
  resources :plots
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plot.rb
class Plot < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user_registration.rb
class UserRegistration < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plots_controller.rb
class PlotsController < ApplicationController
  before_action :set_plot, only: [:show, :edit, :update, :destroy]

  # GET /plots
  # GET /plots.json
  def index
    @plots = Plot.all
  end

  # GET /plots/1
  # GET /plots/1.json
  def show
  end

  # GET /plots/new
  def new
    @plot = Plot.new
  end

  # GET /plots/1/edit
  def edit
  end

  # POST /plots
  # POST /plots.json
  def create
    @plot = Plot.new(plot_params)

    respond_to do |format|
      if @plot.save
        format.html { redirect_to @plot, notice: 'Plot was successfully created.' }
        format.json { render :show, status: :created, location: @plot }
      else
        format.html { render :new }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plots/1
  # PATCH/PUT /plots/1.json
  def update
    respond_to do |format|
      if @plot.update(plot_params)
        format.html { redirect_to @plot, notice: 'Plot was successfully updated.' }
        format.json { render :show, status: :ok, location: @plot }
      else
        format.html { render :edit }
        format.json { render json: @plot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plots/1
  # DELETE /plots/1.json
  def destroy
    @plot.destroy
    respond_to do |format|
      format.html { redirect_to plots_url, notice: 'Plot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plot
      @plot = Plot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plot_params
      # params.fetch(:plot, {})
      params.require(:plot).permit(:plot_Name, :plot_area)
    end
end

app/controllers/user_registrations_controller.rb
class UserRegistrationsController < ApplicationController
  before_action :set_user_registration, only: [:show, :edit, :update, :destroy]

  # GET /user_registrations
  # GET /user_registrations.json
  def index
    @user_registrations = UserRegistration.all
    puts"============ Index ================"
    puts @user_registrations.to_json
    puts"============================"

  end

  # GET /user_registrations/1
  # GET /user_registrations/1.json
  def show
  end

  # GET /user_registrations/new
  def new
    @user_registration = UserRegistration.new
  end

  # GET /user_registrations/1/edit
  def edit
  end

  # POST /user_registrations
  # POST /user_registrations.json
  def create
    @user_registration = UserRegistration.new(user_registration_params)
    puts"=========== Create ================="
    puts @user_registration.to_json
    puts"============================"

    respond_to do |format|
      if @user_registration.save
        # flash[:success] = "User registration was successfully created."
        # redirect_to @user_registration
        format.html { redirect_to @user_registration, notice: 'User registration was successfully created.' }
        format.json { render :show, status: :created, location: @user_registration }
      else
        format.html { render :new }
        format.json { render json: @user_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_registrations/1
  # PATCH/PUT /user_registrations/1.json
  def update
    respond_to do |format|
      puts "*********** update ******************"
      puts user_registration_params
      puts "*****************************"
      if @user_registration.update(user_registration_params)
        format.html { redirect_to @user_registration, notice: 'User registration was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_registration }
      else
        format.html { render :edit }
        format.json { render json: @user_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_registrations/1
  # DELETE /user_registrations/1.json
  def destroy
    @user_registration.destroy
    respond_to do |format|
      format.html { redirect_to user_registrations_url, notice: 'User registration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_registration
      @user_registration = UserRegistration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_registration_params
      # params.permit(:user_name, :state, :District, :taluka, :village,:address)
       params.require(:user_registration).permit(:user_name, :state, :District, :taluka, :village,:address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plot_helper.rb
module PlotHelper
end

app/helpers/plots_helper.rb
module PlotsHelper
end

app/helpers/user_registrations_helper.rb
module UserRegistrationsHelper
	def districts	
		['Ahmednagar','Ahmednagar','Akola','Amravati','Aurangabad','Beed','Bhandara','Buldhana','Chandrapur','Dhule','Gadchiroli','Gondia','Hingoli','Jalgaon','Jalna','Kolhapur','Latur','Mumbai City','Mumbai Suburban','Nagpur','Nanded','Nandurbar','Nashik','Osmanabad','Palghar','Parbhani','Pune','Raigad','Ratnagiri','Sangli','Satara','Sindhudurg','Solapur','Thane','Wardha','Washim','Yavatmal']
	end

	def states
		['Andra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat','Haryana','Himachal Pradesh','Jammu and Kashmir','Jharkhand','Karnataka','Kerala','Madya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Orissa','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telagana','Tripura','Uttaranchal','Uttar Pradesh','West Bengal']
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfarm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plots/_form.html.erb
<%= form_with(model: plot, local: true) do |f| %>
  <% if plot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plot.errors.count, "error") %> prohibited this plot from being saved:</h2>

      <ul>
        <% plot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="form-group col-xs-2">
      <%= f.label :Plot_Name,"Plot Name" %>
    </div>
    <div class="form-group col-sm-10">
      <%= f.text_field :plot_Name ,class: "form-control",placeholder: "Enter Plot Name" %>
    </div>
    <div class="form-group col-xs-2">
      <%= f.label :plot_area, "Plot Area (Acre)" %>
    </div>
    <div class="form-group col-sm-10">
      <%#= f.text_field :plot_area ,class: "form-control",placeholder: "Enter Plot Area" %>
      <%#= f.number_field 'plot_area', nil, in: 1...10 %>
      <%= f.number_field :plot_area, step: :any, class: "form-control" %>
    </div>
    
    <div class="form-group col-xs-2">
      <%= f.submit "Save" , class: "btn btn-success"%>
    </div>

  </div>
<% end %>

app/views/plots/edit.html.erb
<div class="container" style="margin: 30px;">
	<div class="panel panel-primary">
		<div class="panel-heading"> <h4>Editing Plot Information</h4></div>
			<div class="panel-body">

				<%= render 'form', plot: @plot %>

				<%= link_to 'Show', @plot , class: "btn btn-info" %> 
				<%= link_to 'Back', plots_path , class: "btn btn-primary"%>
			</div>
		</div>
	</div>
</div>

app/views/plots/index.html.erb
<div class="container" style="margin: 30px;">
  <div class="panel panel-primary">
    <div class="panel-heading"> <h4>Plots</h4></div>
      <div class="panel-body">

        <p id="notice"><%= notice %></p>

        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th> Id </th>
                <th> Plot name </th>
                <th> Plot Area </th>
                <th> Action </th>
              </tr>
            </thead>

            <tbody>
              <% @plots.each do |plot| %>
                <tr>
                  <td><%= plot.id %></td>
                  <td><%= plot.plot_Name %></td>
                  <td><%= plot.plot_area%></td>
                  <td><%= link_to 'Show', plot , class: "btn btn-info"%></td>
                  <td><%= link_to 'Edit', edit_plot_path(plot), class: "btn btn-primary" %></td>
                  <td><%= link_to 'Destroy', plot, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <br>

        <%= link_to 'New Plot', new_plot_path , class: "btn btn-success"%>
        <%= link_to 'back to user Screen', user_registrations_path , class: "btn btn-success"%>
      </div>
    </div>
  </div>
</div>

app/views/plots/new.html.erb
<div class="container" style="margin: 30px;">
	<div class="panel panel-primary">
		<div class="panel-heading"> <h4>New Plot Information</h4></div>
			<div class="panel-body">
				<%= render 'form', plot: @plot %>

				<%= link_to 'Back', plots_path , class: "btn btn-primary" %>
			</div>
		</div>
	</div>
</div>

app/views/plots/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
	<div class="panel panel-primary">
		<div class="panel-heading"> <h4>Plot Details</h4></div>
			<div class="panel-body">

				<p>
  				<strong>Plot Name:</strong>
				  <%= @plot.plot_Name %>
				</p>
 
				<p>
				  <strong>Address:</strong>
				  <%= @plot.plot_area %>
				</p>

				<%= link_to 'Edit', edit_plot_path(@plot) ,class: "btn btn-success"  %> 
				<%= link_to 'Back', plots_path ,class: "btn btn-primary" %>
			</div>
		</div>
	</div>
</div>

app/views/user_registrations/_form.html.erb
<%= form_with(model: user_registration, local: true) do |form| %>


  <% if user_registration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_registration.errors.count, "error") %> prohibited this user_registration from being saved:</h2>

      <ul>
        <% user_registration.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="form-group col-xs-2">
      <%= form.label :user_name %>
    </div>
    <div class="form-group col-sm-10">
      <%= form.text_field :user_name ,class: "form-control",placeholder: "Enter User Name" %>
    </div>
 
    <div class="form-group col-xs-2">
      <%= form.label :state %>
    </div>
    <div class="form-group col-sm-10">
      <%#= form.select :state, State.all.collect { |p| [ p.state_name, p.id ] }, {:prompt => "--select State--"} ,class: "form-control"%>
      <%= form.select :state, options_for_select(states,:selected => form.object.state),{:prompt => "--select State--"},class: "form-control"  %>
    </div>
    <div class="form-group col-xs-2">
      <%= form.label :District %>
    </div>
    <div class="form-group col-sm-10">
      <%= form.select :District, options_for_select(districts, :selected => form.object.District),{:prompt => "--select Districts--"},class: "form-control"  %>
    </div>
    <div class="form-group col-xs-2">
      <%= form.label :taluka %>
    </div>
    <div class="form-group col-sm-10">
      <%= form.text_field :taluka ,class: "form-control"%>
    </div>
    <div class="form-group col-xs-2">
      <%= form.label :village %>
    </div>
    <div class="form-group col-sm-10">
      <%= form.text_field :village ,class: "form-control"%>
    </div>
    <div class="form-group col-xs-2">
      <%= form.label :address %>
    </div>
    <div class="form-group col-sm-10">
      <%= form.text_field :address ,class: "form-control"%>
    </div>
  
    <div class="form-group col-xs-2">
      <%= form.submit "Register", class: "btn btn-success"%>
    </div>
  </div>


<% end %>

app/views/user_registrations/edit.html.erb
<div class="container" style="margin: 30px;">
	<div class="panel panel-primary">
		<div class="panel-heading"> <h4>Editing User Registration</h4></div>
			<div class="panel-body">
				<%= render 'form', user_registration: @user_registration %>
			</div>
			<div>
				<%= link_to 'Show', @user_registration , class: "btn btn-info" %> 
				<%= link_to 'Back', user_registrations_path , class: "btn btn-primary" %>
			</div>
		</div>
	</div>
</div>

app/views/user_registrations/index.html.erb
<div class="container" style="margin: 30px;">
  <div class="panel panel-primary">
    <div class="panel-heading"> <h4>User List</h4></div>
      <div class="panel-body">

        <p id="notice"><%= notice %></p>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th> ID </th>
                <th> User Name </th>
                <th> Address </th>
                <th> Action </th>
              </tr>
            </thead>

            <tbody>
              <% @user_registrations.each do |user_registration| %>
                <tr>
                  <td><%= user_registration.id %></td>
                  <td><%= user_registration.user_name %></td>
                  <td><%= user_registration.address %></td>
                  <td><%= link_to 'Show', user_registration , class: "btn btn-info" %></td>
                  <td><%= link_to 'Edit', edit_user_registration_path(user_registration), class: "btn btn-primary" %></td>
                  <td><%= link_to 'Destroy', user_registration, method: :delete, data: { confirm: 'Are you sure?'} ,class: "btn btn-danger"%></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <br>

        <%= link_to 'New User Registration', new_user_registration_path ,class: "btn btn-success"%>
        <%= link_to 'Plot Registration',new_plot_path , class: "btn btn-primary" %>
        <!-- link_to "Profile", controller: "profiles", action: "show", id: @profile -->
      </div>
    </div>
  </div>
  

app/views/user_registrations/new.html.erb
<div class="container" style="margin: 30px;">
	<div class="panel panel-primary">
		<div class="panel-heading"> <h4>New User Registration</h4></div>
			<div class="panel-body">
				<%= render 'form', user_registration: @user_registration %>
			</div>
		</div>
		<%= link_to 'Back', user_registrations_path ,class: "btn btn-primary" %>
	</div>
</div>

app/views/user_registrations/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
	<div class="panel panel-primary">
		<div class="panel-heading"> <h4>User Details</h4></div>
			<div class="panel-body">
				<p>
  				<strong>User Name:</strong>
				  <%= @user_registration.user_name %>
				</p>
 
				<p>
				  <strong>Address:</strong>
				  <%= @user_registration.address %>
				</p>

				<%= link_to 'Edit', edit_user_registration_path(@user_registration),class: "btn btn-success" %> 
				<%= link_to 'Back', user_registrations_path , class: "btn btn-primary" %>
			</div>
		</div>
	</div>
</div>